//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PatientManagementDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class PatientEnrollment
    {
        public int ID { get; set; }
        public int PatientID { get; set; }
        public int TestID { get; set; }
        public System.DateTime EnrolledOn { get; set; }
        public bool IsActive { get; set; }
    
        public virtual Patient Patient { get; set; }
        public virtual Test Test { get; set; }
    }
}
